### ISSUE TITLE
VSCode extension - multible accounts switching

### ISSUE THREAD

**Issue by Sharaf5** [a85/POSTMan-Chrome-Extension#12302]
### Is there an existing request for this feature?

- [x] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

In VSCode extention one can't switch between his personal account and team login

![image](https://github.com/postmanlabs/postman-app-support/assets/36330265/af8aa02d-6521-4600-9e4f-5894df51cd60)
![Screenshot_20230909_105058](https://github.com/postmanlabs/postman-app-support/assets/36330265/5ba517b7-ddcb-46bf-a17e-1655a2b12889)
![Screenshot_20230909_105157](https://github.com/postmanlabs/postman-app-support/assets/36330265/540a8192-c0e3-4f88-b18e-1d4f1d0b2e26)
****

### Describe the solution you'd like

The same as the site
An easy way to switch between teams, and personal accounts

![image](https://github.com/postmanlabs/postman-app-support/assets/36330265/7b32ffce-0961-4773-8da9-4c48579d865b)

### Describe alternatives you've considered

for now one must logout and login agian
however we could switch smoothly on the site

```[tasklist]
### Tasks
- [ ] Handle multible tokens independantly
- [ ] Multible accounts switching without logout
```
